export const BOOK_AC_SERVICE = 'BOOK_AC_SERVICE';
export const GET_AC_SERVICE_BOOKINGS = 'GET_AC_SERVICE_BOOKINGS';
export const UPDATE_BOOK_AC_SERVICE = 'UPDATE_BOOK_AC_SERVICE';
export const ADD_USER = 'ADD_USER';